---
# handlers file for frontend/
- name: Restart sshd
  become: true
  service:
    name: sshd
    state: restarted

- name: Restart apache2
  become: true
  service:
    name: apache2
    enabled: yes
    state: restarted
